apiVersion: v1
kind: Service
metadata:
  name: http-8080
spec:
  selector:
    kubevirt.io/domain: rhel8-vm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: http-8081
spec:
  selector:
    kubevirt.io/domain: rhel8-vm
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081
