kind: Service
apiVersion: v1
metadata:
  name: rhel8-vm-ssh-service
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ports:
    - protocol: TCP
      port: 22000
      targetPort: 22
  internalTrafficPolicy: Cluster
  type: NodePort
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    kubevirt.io/domain: rhel8-vm